version: '3'
#volumes: 
#  data:
services:
  web:
    build: .
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - '.:/develop'
    tty: true
    stdin_open: true
    environment:
      - 'DATABASE_PASSWORD=password' 
    depends_on: 
      - db
    links:
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - '23306:3306'
    volumes:
      - './mysql/data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
